import { alpha, lighten } from '@theme-ui/color'
import logobgUrl from '~/public/logo-bg.svg'

const styles = {
    section: {
        position: 'relative',
        mt: t => [`-${t.space.header}`, null, 0],
        pt: [7, null, 13, null, '7em'],
        bg: ['background', null, 'secondary.pale'],
        backgroundImage: [null, null, `url('${logobgUrl}')`],
        backgroundSize: '170%',
        backgroundAttachment: 'fixed',
        borderTopLeftRadius: [40, null, 'none'],
        borderTopRightRadius: [40, null, 'none'],
        '.wave-decoration': {
            display: ['none', null, 'block'],
        },
        '.scrollable': {
            flexWrap: ['nowrap', null, 'wrap'],
            justifyContent: [null, null, 'center'],
            textAlign: 'center',
            mt: '-1.5em',
            mb: [null, null, 8],
            mx: ['-1.5em', null, 'auto'],
            pb: [6, null, 1],
            minWidth: 0,
            maxWidth: 'container',
        },
    },
    stackContext: {
        position: 'relative',
        zIndex: 1,
    },
    header: {
        display: [null, null, 'none'],
        mb: 0,
        mx: [null, null, 3],
    },
    topOffer: {
        position: 'relative',
        minHeight: '10em',
        background: t => [
            t.colors.heroStripe3,
            null,
            null,
            null,
            `linear-gradient(to right, ${t.colors.heroStripe3} 50%, ${t.colors.heroStripe2} 50%)`,
        ],
        color: 'heroText',
        borderRadius: ['default', null, '20'],
        padding: 6,
        mt: [6, null, 0],
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        lineHeight: 'snug',
        '::before,::after': {
            content: '""',
            position: 'absolute',
            top: 0,
            borderRadius: 'inherit',
            zIndex: '-1',
        },
        '&:before': {
            width: '85%',
            height: '109%', // '113%',
            bg: t => lighten('secondary.base', 0.7)(t),
        },
        '&:after': {
            width: '92%',
            height: '105%', // '107%',
            bg: t => lighten('secondary.base', 0.55)(t),
        },
        '& > span': {
            position: 'absolute',
            size: '1em',
            color: ['primary.base', null, 'accent.base'],
        },
        '& > span:first-of-type': {
            top: '1em',
            left: '1em',
            borderTop: '1.5px solid',
            borderLeft: '1.5px solid',
        },
        '& > span:last-of-type': {
            bottom: '1em',
            right: '1em',
            borderRight: '1.5px solid',
            borderBottom: '1.5px solid',
        },
    },
    offersCard: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        flex: '0 0 auto',
        maxWidth: '9em',
        mt: 4,
        mx: 2,
        padding: ['1.25em', null, 4],
        bg: 'primary.base',
        border: t => [null, null, `1px solid ${t.colors.primary.hover}`],
        borderRadius: ['circle', null, 'tiny'],
        boxShadow: t => [`0 15px 20px -5px ${alpha('primary.base', 0.5)(t)}`, null, 'none'],
        cursor: 'pointer',
        transition: 'background-color 0.4s ease-out, transform 0.4s ease-out',
        backfaceVisibility: 'hidden',
        transformStyle: 'preserve-3d',
        ':hover': {
            bg: 'primary.hover',
            transform: 'scale(1.05)',
        },
        p: {
            fontSize: [null, null, 1],
        },
        'p span': {
            display: 'block',
            fontSize: [null, null, 3],
        },
    },
}
export default styles
